security:
    encoders:
        Fewnix\UserBundle\Entity\User:
            algorithm: sha512
            encode_as_base64: false
            iterations: 10

    role_hierarchy:
            ROLE_ADMIN: ROLE_TEACHER
            ROLE_ADMIN: ROLE_STUDENT

    providers:
            fos_userbundle:
                id: fos_user.user_manager
            main:
              entity:
                  class: Fewnix\UserBundle\Entity\User
                  property: email

    firewalls:
            api:
                pattern:    ^/api
                fos_oauth:  true
                stateless:  true
                anonymous:  true

            oauth_token:
                pattern:    ^/oauth/v2/token
                security:   false

            oauth_authorize:
                pattern: ^/oauth/v2/auth
                form_login:
                    provider: fos_userbundle
                    check_path: /oauth/v2/auth_login_check
                    login_path: /oauth/v2/auth_login
                    use_referer: true
                anonymous: true

    access_control:
        - { path: ^/oauth/v2/auth_login$, role: IS_AUTHENTICATED_ANONYMOUSLY }

        - { path: ^/api/v1/*, roles: [ IS_AUTHENTICATED_ANONYMOUSLY ] }

        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }